"""Initial Phase 1 schema — all platform, config and operational tables.

Creates the complete Phase 1 schema (24 tables) defined by the SQLAlchemy
models. Because this is the very first migration and the models are the single
source of truth, upgrade()/downgrade() create/drop the full metadata in FK
dependency order via the bound engine. Subsequent migrations will be ordinary
autogenerated diffs against this baseline.

Revision ID: ebb08c79944f
Revises:
Create Date: 2026-06-12

"""
from alembic import op
import sqlalchemy as sa
from flask import current_app


# revision identifiers, used by Alembic.
revision = 'ebb08c79944f'
down_revision = None
branch_labels = None
depends_on = None


def _metadata():
    return current_app.extensions['migrate'].db.metadata


def upgrade():
    bind = op.get_bind()
    meta = _metadata()
    # checkfirst=False: this is the baseline; tables must not already exist.
    meta.create_all(bind=bind, checkfirst=False)


def downgrade():
    bind = op.get_bind()
    meta = _metadata()
    meta.drop_all(bind=bind)
    # Drop the PostgreSQL ENUM types created for the enum columns, which
    # drop_all() does not remove automatically.
    for enum_name in (
        'school_status', 'user_role', 'student_status', 'attendance_status',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
