"""Phase 2: notification settings + log tables.

Adds school_notification_settings (per-school SMTP + SMS sender),
platform_settings (super-admin key/value: platform SMTP + Vynfy bridge), and
notification_logs (record of every send).

Hand-written (not autogenerated) because the initial Phase 1 migration uses
metadata.create_all(), so autogenerate sees no diff once those tables already
exist. This migration is idempotent-friendly: it only creates the three new
tables.

Revision ID: ed1b8bd275c0
Revises: ebb08c79944f
Create Date: 2026-06-18
"""
from alembic import op
import sqlalchemy as sa


revision = 'ed1b8bd275c0'
down_revision = 'ebb08c79944f'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing = set(insp.get_table_names())

    if 'school_notification_settings' not in existing:
        op.create_table(
            'school_notification_settings',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('school_id', sa.Integer(),
                      sa.ForeignKey('schools.id', ondelete='CASCADE'),
                      nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('smtp_enabled', sa.Boolean(), nullable=False,
                      server_default=sa.false()),
            sa.Column('smtp_host', sa.String(length=255)),
            sa.Column('smtp_port', sa.Integer()),
            sa.Column('smtp_use_tls', sa.Boolean(), nullable=False,
                      server_default=sa.true()),
            sa.Column('smtp_username', sa.String(length=255)),
            sa.Column('smtp_password_enc', sa.Text()),
            sa.Column('smtp_from_email', sa.String(length=255)),
            sa.Column('smtp_from_name', sa.String(length=255)),
            sa.Column('sms_enabled', sa.Boolean(), nullable=False,
                      server_default=sa.false()),
            sa.Column('sms_sender_id', sa.String(length=11)),
            sa.UniqueConstraint('school_id', name='uq_notif_settings_school'),
        )
        op.create_index('ix_school_notification_settings_school_id',
                        'school_notification_settings', ['school_id'])

    if 'platform_settings' not in existing:
        op.create_table(
            'platform_settings',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('key', sa.String(length=100), nullable=False),
            sa.Column('value', sa.Text()),
            sa.Column('value_enc', sa.Text()),
            sa.UniqueConstraint('key', name='uq_platform_settings_key'),
        )
        op.create_index('ix_platform_settings_key', 'platform_settings',
                        ['key'], unique=True)

    if 'notification_logs' not in existing:
        op.create_table(
            'notification_logs',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('school_id', sa.Integer(),
                      sa.ForeignKey('schools.id', ondelete='SET NULL'),
                      nullable=True),
            sa.Column('channel', sa.String(length=20), nullable=False),
            sa.Column('recipient', sa.String(length=255), nullable=False),
            sa.Column('subject', sa.String(length=255)),
            sa.Column('message', sa.Text()),
            sa.Column('provider', sa.String(length=40)),
            sa.Column('provider_message_id', sa.String(length=120)),
            sa.Column('status', sa.String(length=20), nullable=False,
                      server_default='queued'),
            sa.Column('error', sa.Text()),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Index('ix_notification_logs_school_id', 'school_id'),
            sa.Index('ix_notification_logs_status', 'status'),
            sa.Index('ix_notification_logs_created_at', 'created_at'),
        )


def downgrade():
    op.drop_table('notification_logs')
    op.drop_index('ix_platform_settings_key', table_name='platform_settings')
    op.drop_table('platform_settings')
    op.drop_index('ix_school_notification_settings_school_id',
                  table_name='school_notification_settings')
    op.drop_table('school_notification_settings')
